custom:
  NettyPort: 8768
  RedisAddress: 10.0.0.6
  RedisPort: 6379
  MysqlPassword: 123456
  RedisPassword: null
  MysqlURL: jdbc:mysql://10.0.0.6:33060/Charge?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  MysqlUsername: root
  WebPort: 80

server:
  port: "${custom.WebPort}"
  shutdown: graceful

spring:
  datasource:
    password: "${custom.MysqlPassword}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "${custom.MysqlURL}"
    username: "${custom.MysqlUsername}"
