custom:
  NettyPort: 8768
  RedisAddress: 10.0.0.6
  RedisPort: 6379
  MongoAddress: 10.0.0.6
  MongoPort: 27017
  MongoDataBase: "Charge"

server:
  port: 8686
spring:
  data:
    mongodb:
      host: ${custom.MongoAddress}
      port: ${custom.MongoPort}
      database: ${custom.MongoDataBase}